package msgDTO

const (
	ORDER_EVENT_COMMIT_SUCCESS    = 1
	ORDER_EVENT_FAIL_BY_PRODUCT   = 2
	ORDER_EVENT_FAIL_BY_PROMOTION = 3
	ORDER_EVENT_FAIL_BY_DELIVERY  = 4
	ORDER_EVENT_FAIL_BY_PAYMENT   = 5
	ORDER_EVENT_CANCEL            = 6
	ORDER_EVENT_REFUND            = 7
)
