// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: internal/infrastructure/grpc/promotionServ/voucher_grpc.proto

package vouchergrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoucherServiceGRPCClient is the client API for VoucherServiceGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceGRPCClient interface {
	CheckingVoucher(ctx context.Context, in *CheckingVoucherRequest, opts ...grpc.CallOption) (*CheckingVoucherResponse, error)
	ApplyVoucher(ctx context.Context, in *UseVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error)
}

type voucherServiceGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceGRPCClient(cc grpc.ClientConnInterface) VoucherServiceGRPCClient {
	return &voucherServiceGRPCClient{cc}
}

func (c *voucherServiceGRPCClient) CheckingVoucher(ctx context.Context, in *CheckingVoucherRequest, opts ...grpc.CallOption) (*CheckingVoucherResponse, error) {
	out := new(CheckingVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherServiceGRPC/CheckingVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceGRPCClient) ApplyVoucher(ctx context.Context, in *UseVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error) {
	out := new(ApplyVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherServiceGRPC/ApplyVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceGRPCServer is the server API for VoucherServiceGRPC service.
// All implementations must embed UnimplementedVoucherServiceGRPCServer
// for forward compatibility
type VoucherServiceGRPCServer interface {
	CheckingVoucher(context.Context, *CheckingVoucherRequest) (*CheckingVoucherResponse, error)
	ApplyVoucher(context.Context, *UseVoucherRequest) (*ApplyVoucherResponse, error)
	mustEmbedUnimplementedVoucherServiceGRPCServer()
}

// UnimplementedVoucherServiceGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceGRPCServer struct {
}

func (UnimplementedVoucherServiceGRPCServer) CheckingVoucher(context.Context, *CheckingVoucherRequest) (*CheckingVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckingVoucher not implemented")
}
func (UnimplementedVoucherServiceGRPCServer) ApplyVoucher(context.Context, *UseVoucherRequest) (*ApplyVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVoucher not implemented")
}
func (UnimplementedVoucherServiceGRPCServer) mustEmbedUnimplementedVoucherServiceGRPCServer() {}

// UnsafeVoucherServiceGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceGRPCServer will
// result in compilation errors.
type UnsafeVoucherServiceGRPCServer interface {
	mustEmbedUnimplementedVoucherServiceGRPCServer()
}

func RegisterVoucherServiceGRPCServer(s grpc.ServiceRegistrar, srv VoucherServiceGRPCServer) {
	s.RegisterService(&VoucherServiceGRPC_ServiceDesc, srv)
}

func _VoucherServiceGRPC_CheckingVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckingVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceGRPCServer).CheckingVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherServiceGRPC/CheckingVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceGRPCServer).CheckingVoucher(ctx, req.(*CheckingVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherServiceGRPC_ApplyVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceGRPCServer).ApplyVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherServiceGRPC/ApplyVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceGRPCServer).ApplyVoucher(ctx, req.(*UseVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherServiceGRPC_ServiceDesc is the grpc.ServiceDesc for VoucherServiceGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherServiceGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoucherServiceGRPC",
	HandlerType: (*VoucherServiceGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckingVoucher",
			Handler:    _VoucherServiceGRPC_CheckingVoucher_Handler,
		},
		{
			MethodName: "ApplyVoucher",
			Handler:    _VoucherServiceGRPC_ApplyVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/grpc/promotionServ/voucher_grpc.proto",
}
