// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: internal/infrastructure/grpc/promotionServ/voucher_grpc.proto

package vouchergrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceClient interface {
	CheckingVoucher(ctx context.Context, in *CheckingVoucherRequest, opts ...grpc.CallOption) (*CheckingVoucherResponse, error)
	ApplyVoucher(ctx context.Context, in *UseVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) CheckingVoucher(ctx context.Context, in *CheckingVoucherRequest, opts ...grpc.CallOption) (*CheckingVoucherResponse, error) {
	out := new(CheckingVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherService/CheckingVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ApplyVoucher(ctx context.Context, in *UseVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error) {
	out := new(ApplyVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherService/ApplyVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceServer is the server API for VoucherService service.
// All implementations must embed UnimplementedVoucherServiceServer
// for forward compatibility
type VoucherServiceServer interface {
	CheckingVoucher(context.Context, *CheckingVoucherRequest) (*CheckingVoucherResponse, error)
	ApplyVoucher(context.Context, *UseVoucherRequest) (*ApplyVoucherResponse, error)
	mustEmbedUnimplementedVoucherServiceServer()
}

// UnimplementedVoucherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (UnimplementedVoucherServiceServer) CheckingVoucher(context.Context, *CheckingVoucherRequest) (*CheckingVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckingVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) ApplyVoucher(context.Context, *UseVoucherRequest) (*ApplyVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) mustEmbedUnimplementedVoucherServiceServer() {}

// UnsafeVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceServer will
// result in compilation errors.
type UnsafeVoucherServiceServer interface {
	mustEmbedUnimplementedVoucherServiceServer()
}

func RegisterVoucherServiceServer(s grpc.ServiceRegistrar, srv VoucherServiceServer) {
	s.RegisterService(&VoucherService_ServiceDesc, srv)
}

func _VoucherService_CheckingVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckingVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).CheckingVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherService/CheckingVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).CheckingVoucher(ctx, req.(*CheckingVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ApplyVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ApplyVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherService/ApplyVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ApplyVoucher(ctx, req.(*UseVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherService_ServiceDesc is the grpc.ServiceDesc for VoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckingVoucher",
			Handler:    _VoucherService_CheckingVoucher_Handler,
		},
		{
			MethodName: "ApplyVoucher",
			Handler:    _VoucherService_ApplyVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/grpc/promotionServ/voucher_grpc.proto",
}
