// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: internal/infrastructure/grpc/promotionServ/voucher_grpc.proto

package vouchergrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceClient interface {
	CheckoutVoucherForPurchase(ctx context.Context, in *CheckoutVoucherRequest, opts ...grpc.CallOption) (*CheckoutVoucherResponse, error)
	ApplyVoucherToPurchase(ctx context.Context, in *ApplyVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) CheckoutVoucherForPurchase(ctx context.Context, in *CheckoutVoucherRequest, opts ...grpc.CallOption) (*CheckoutVoucherResponse, error) {
	out := new(CheckoutVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherService/CheckoutVoucherForPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ApplyVoucherToPurchase(ctx context.Context, in *ApplyVoucherRequest, opts ...grpc.CallOption) (*ApplyVoucherResponse, error) {
	out := new(ApplyVoucherResponse)
	err := c.cc.Invoke(ctx, "/VoucherService/ApplyVoucherToPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceServer is the server API for VoucherService service.
// All implementations must embed UnimplementedVoucherServiceServer
// for forward compatibility
type VoucherServiceServer interface {
	CheckoutVoucherForPurchase(context.Context, *CheckoutVoucherRequest) (*CheckoutVoucherResponse, error)
	ApplyVoucherToPurchase(context.Context, *ApplyVoucherRequest) (*ApplyVoucherResponse, error)
	mustEmbedUnimplementedVoucherServiceServer()
}

// UnimplementedVoucherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (UnimplementedVoucherServiceServer) CheckoutVoucherForPurchase(context.Context, *CheckoutVoucherRequest) (*CheckoutVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckoutVoucherForPurchase not implemented")
}
func (UnimplementedVoucherServiceServer) ApplyVoucherToPurchase(context.Context, *ApplyVoucherRequest) (*ApplyVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVoucherToPurchase not implemented")
}
func (UnimplementedVoucherServiceServer) mustEmbedUnimplementedVoucherServiceServer() {}

// UnsafeVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceServer will
// result in compilation errors.
type UnsafeVoucherServiceServer interface {
	mustEmbedUnimplementedVoucherServiceServer()
}

func RegisterVoucherServiceServer(s grpc.ServiceRegistrar, srv VoucherServiceServer) {
	s.RegisterService(&VoucherService_ServiceDesc, srv)
}

func _VoucherService_CheckoutVoucherForPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).CheckoutVoucherForPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherService/CheckoutVoucherForPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).CheckoutVoucherForPurchase(ctx, req.(*CheckoutVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ApplyVoucherToPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ApplyVoucherToPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoucherService/ApplyVoucherToPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ApplyVoucherToPurchase(ctx, req.(*ApplyVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherService_ServiceDesc is the grpc.ServiceDesc for VoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckoutVoucherForPurchase",
			Handler:    _VoucherService_CheckoutVoucherForPurchase_Handler,
		},
		{
			MethodName: "ApplyVoucherToPurchase",
			Handler:    _VoucherService_ApplyVoucherToPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/grpc/promotionServ/voucher_grpc.proto",
}
