// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"encoding/json"
	"github.com/ansrivas/fiberprometheus/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"latipe-order-service-v2/config"
	order2 "latipe-order-service-v2/internal/api/order"
	"latipe-order-service-v2/internal/app/orders"
	"latipe-order-service-v2/internal/common/errors"
	"latipe-order-service-v2/internal/infrastructure/adapter/authserv"
	"latipe-order-service-v2/internal/infrastructure/adapter/deliveryserv"
	"latipe-order-service-v2/internal/infrastructure/adapter/productserv"
	"latipe-order-service-v2/internal/infrastructure/adapter/storeserv"
	"latipe-order-service-v2/internal/infrastructure/adapter/userserv"
	"latipe-order-service-v2/internal/infrastructure/adapter/vouchersev"
	"latipe-order-service-v2/internal/infrastructure/persistence/db"
	"latipe-order-service-v2/internal/infrastructure/persistence/order"
	"latipe-order-service-v2/internal/middleware"
	"latipe-order-service-v2/internal/middleware/auth"
	"latipe-order-service-v2/internal/msgqueue"
	"latipe-order-service-v2/internal/router"
	"latipe-order-service-v2/internal/worker"
	"latipe-order-service-v2/pkg/cache"
	"latipe-order-service-v2/pkg/rabbitclient"
)

// Injectors from server.go:

func New() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	gorm := db.NewMySQLConnection(configConfig)
	repository := order.NewGormRepository(gorm)
	service := productserv.NewProductServAdapter(configConfig)
	cacheEngine, err := cache.NewCacheEngine(configConfig)
	if err != nil {
		return nil, err
	}
	userservService := userserv.NewUserServHttpAdapter(configConfig)
	deliveryservService := deliveryserv.NewDeliServHttpAdapter(configConfig)
	voucherservService := voucherserv.NewUserServHttpAdapter(configConfig)
	connection := rabbitclient.NewRabbitClientConnection(configConfig)
	publisherTransactionMessage := msgqueue.NewTransactionProducer(configConfig, connection)
	usecase := orders.NewOrderService(configConfig, repository, service, cacheEngine, userservService, deliveryservService, voucherservService, publisherTransactionMessage)
	orderApiHandler := order2.NewOrderHandler(usecase)
	orderStatisticApiHandler := order2.NewStatisticHandler(usecase)
	authservService := authserv.NewAuthServHttpAdapter(configConfig)
	storeservService := storeserv.NewStoreServiceAdapter(configConfig)
	authenticationMiddleware := auth.NewAuthMiddleware(authservService, storeservService, deliveryservService, configConfig)
	middlewareMiddleware := middleware.NewMiddleware(authenticationMiddleware)
	orderRouter := router.NewOrderRouter(orderApiHandler, orderStatisticApiHandler, middlewareMiddleware)
	orderTransactionSubscriber := worker.NewOrderTransactionSubscriber(configConfig, connection, usecase)
	server := NewServer(configConfig, orderRouter, orderTransactionSubscriber)
	return server, nil
}

// server.go:

type Server struct {
	app       *fiber.App
	cfg       *config.Config
	orderSubs *worker.OrderTransactionSubscriber
}

func NewServer(
	cfg *config.Config,
	orderRouter router.OrderRouter,
	orderSubs *worker.OrderTransactionSubscriber) *Server {

	app := fiber.New(fiber.Config{
		ReadTimeout:  cfg.Server.ReadTimeout,
		WriteTimeout: cfg.Server.WriteTimeout,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
		ErrorHandler: errors.CustomErrorHandler,
	})

	prometheus := fiberprometheus.New("latipe-order-service-v2")
	prometheus.RegisterAt(app, "/metrics")
	app.Use(prometheus.Middleware)

	app.Use(logger.New())

	app.Get("", func(ctx *fiber.Ctx) error {
		s := struct {
			Message string `json:"message"`
			Version string `json:"version"`
		}{
			Message: "Order rest-api was developed by TienDat",
			Version: "v2.0.0",
		}
		return ctx.JSON(s)
	})

	api := app.Group("/api")
	v2 := api.Group("/v2")

	orderRouter.Init(&v2)

	return &Server{
		cfg:       cfg,
		app:       app,
		orderSubs: orderSubs,
	}
}

func (serv Server) App() *fiber.App {
	return serv.app
}

func (serv Server) Config() *config.Config {
	return serv.cfg
}

func (serv Server) OrderTransactionSubscriber() *worker.OrderTransactionSubscriber {
	return serv.orderSubs
}
